name: CI

on:
  pull_request: 
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add Yarn package repo
      run: |
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - name: Install npm and yarn
      run: sudo apt update -y && sudo apt install -y yarn
    - name: Install app
      run: yarn install
    - name: Run unit tests
      run: yarn run test:unit
